SELECT * FROM USUARIOS;

-- GET
SELECT ID,
	   NOMEUSUARIO,
       SENHA,
       ID_CATEGORIA,
       ID_SITUACAO
  FROM USUARIOS
 WHERE ID = 1;

-- INSERT
INSERT INTO USUARIOS
( NOMEUSUARIO, SENHA, ID_CATEGORIA, ID_SITUACAO )
VALUES
( @P_NOMEUSUARIO, @P_SENHA, @P_ID_CATEGORIA, @P_ID_SITUACAO );

-- UPDATE
UPDATE USUARIOS
   SET NOMEUSUARIO = @P_NOMEUSUARIO,
	   SENHA = @P_SENHA,
       ID_CATEGORIA = @P_ID_CATEGORIA,
       ID_SITUACAO = @P_ID_SITUACAO
 WHERE ID = @P_ID;

-- DELETE
-- NÃO FAZER! ALTERAR A SITUAÇÃO DO USUÁRIO PARA DESATIVADO


